version: "3"
services:
  arangodb:
    image: arangodb:3.11.1
    environment:
      - ARANGO_ROOT_PASSWORD=test123
    ports:
      - 8529:8529
    volumes:
      - /home/chad/dev/Incubyte/code-aid-db-output:/var/lib/arangodb3
  code-aid-site:
    depends_on:
      - arangodb
    image: code-aid-site:latest
    environment:
      - args_include=*.java
      - FILTER=*.java
      - datasources_default_url=jdbc:sqlserver://host.docker.internal:1433;database=AdventureWorks2019
      - datasources_default_username=sonar1
      - datasources_default_password=sonartest
      - datasources_arangodb_host=arangodb
    volumes:
      - C:\Users\DELL\Desktop\jar-for-code-aid\Glowstone:/input
    working_dir: /code-aid-parser
    ports:
      - 1313:1313
    command:
      - sh
      - -c
      - |
        node src/main.js &&
        cd /code-aid &&
        java -jar app.jar &&
        cd /code-aid-db &&
        java -jar app.jar &&
        cd /code-aid-site &&
        cp -r /code-aid-db/markdownOutput /code-aid-site/content/en/docs &&
        cp -r /code-aid-output /code-aid-site/content/en/docs &&
        hugo server --bind 0.0.0.0
        
