version: "3"
services:
  arangodb:
    image: arangodb:3.11.1
    environment:
      - ARANGO_ROOT_PASSWORD=test123
    ports:
      - 8529:8529
    volumes:
      - ${BASE_FOLDER}\arangodbbackup:/var/lib/arangodb3
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - 6333:6333
    volumes:
      - ${BASE_FOLDER}\qdrant:/data
  semgrep:
    image: returntocorp/semgrep:latest
    volumes:
      - ${CODEBASE_DIR}:/src
      - ${BASE_FOLDER}\security-output:/output
    command:
      - sh
      - -c
      - |
        semgrep --config=auto --json --output=/output/scan_results.json
  code-embeddings:
    image: code-embeddings:latest
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ARANGODB_URL=http://arangodb:8529
      - QDRANT_URL=http://qdrant:6333
      - ARANGODB_NAME=code-embedding
    ports:
      - 3000:3000
    command:
      - sh
      - -c
      - |
        ./wait-for-arangodb.sh arangodb 8529 root test123 &&
        ./wait-for-qdrant.sh qdrant 6333 &&
        curl -X DELETE http://host.docker.internal:6333/collections/code &&
        npm install &&
        node main.js
  code-aid:
    depends_on:
      - code-embeddings
    image: code-aid:latest
    working_dir: /code-aid-parser
    environment:
      - args_include=*.java
      - args_parsedjson=/code-aid-parser-output
      - args_output=/${OUTPUT_DIR_NAME}
      - args_input=/input
      - args_codeembeddingscollection=code
      - FILTER=*.java
      - INPUT_DIR=/input
      - OUTPUT_DIR=/code-aid-parser-output
      - datasources_arangodb_host=arangodb
      - args_codeembeddingsurl=http://code-embeddings:3000
    volumes:
      - ${CODEBASE_DIR}:/input
      - ${BASE_FOLDER}\${OUTPUT_DIR_NAME}:/${OUTPUT_DIR_NAME}
    command:
      - sh
      - -c
      - |
        rm -rf /${OUTPUT_DIR_NAME}/ready &&
        npm ci &&
        node src/main.js &&
        cd /code-aid &&
        java -jar app.jar &&
        touch /${OUTPUT_DIR_NAME}/ready
  code-aid-site:
    depends_on:
      - code-aid
    image: code-aid-site:latest
    ports:
      - 1313:1313
    volumes:
      - ${BASE_FOLDER}\${OUTPUT_DIR_NAME}:/code-aid-site/content/en/docs/Code/${OUTPUT_DIR_NAME}
      - ${BASE_FOLDER}\security-output:/security-issues
    command:
      - sh
      - -c
      - |
        ./wait-for-code-aid-finish.sh /code-aid-site/content/en/docs/Code/${OUTPUT_DIR_NAME}/ready &&
        ./generate-architecture-diagram.sh ${OUTPUT_DIR_NAME} &&
        ./generate-security-issues.sh ${OUTPUT_DIR_NAME} &&
        hugo server --bind 0.0.0.0
